### ISSUE TITLE
how to fix wrong disposable bag branch problem

### ISSUE THREAD

**Issue by ShRoO0oM** [arasmarko/mvvm-rx-demo#2]
So how do you fix wrong disposable bag branch problem ( the one you added with gesture )?
I tried with cell.disposeBag but no difference.

thanks for your great article.

**Comment by arasmarko** [comment]
I think you will be able to find the answer in this article http://arsfutura.co/magazine/mvvm-with-rxswift/.

**Comment by mohammadZ74** [comment]
I read your article but in the disposable bag branch you added gesture and I didn't find anything related 🤔

**Comment by arasmarko** [comment]
Did you initialize new DisposeBag when setting up the cell?

**Comment by ShRoO0oM** [comment]
yes but problem remains 🤔

**Comment by ShRoO0oM** [comment]
Actually its another problem and nothing will printed ( when I crating disposable bag in setting up cell )

**Comment by arasmarko** [comment]
in the HomeViewController.setupTableView you need to change self.disposeBag to cell.disposeBag,
and in the HomeTableViewCell.setupInfo you need to add a line disposeBag = DisposeBag().
This is so the previous subscription can be disposed.

**Comment by arasmarko** [comment]
I just pushed a solution to the `wrong-dispose-bag` branch so you can look it up

**Comment by ShRoO0oM** [comment]
thanks.. I didn't add `disposeBag = DisposeBag()` to cell setupInfo and was just relying to disposable bag init in HomeTableViewCell .

**Comment by ShRoO0oM** [comment]
sorry for reopening but I was wondering why the previous method ( without adding in setupInfo ) and just using cell.disposeBag , wasn't working?

**Comment by arasmarko** [comment]
Just think of the lifecycle of the cell object, and as long as it exists, his disposeBag exist, and it "remembers" all subscriptions that were added into it. By doing disposeBag = DisposeBag(), you are disposing("killing") all the previous subscriptions.
